Tweak configs, add some functions

diff --git a/runcoms/zshrc b/runcoms/zshrc
--- a/runcoms/zshrc
+++ b/runcoms/zshrc
@@ -8,16 +8,20 @@
 ####################################################################################
 #  POWERLEVEL9K
 
-POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon status dir vcs)
-POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(background_jobs time)
+POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon dir vcs)
+POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status background_jobs time swift_version)
 
 POWERLEVEL9K_MODE='awesome-fontconfig'
 
 POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0C6'
 POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0C7'
+POWERLEVEL9K_SWIFT_ICON='\uE755 '
+POWERLEVEL9K_APPLE_ICON='\uF179 '
+
 POWERLEVEL9K_HOME_ICON=''
 POWERLEVEL9K_HOME_SUB_ICON=''
 POWERLEVEL9K_FOLDER_ICON=''
+POWERLEVEL9K_HOME_FOLDER_ABBREVIATION='\uF015 '
 
 POWERLEVEL9K_SHORTEN_STRATEGY="truncate_middle"
 POWERLEVEL9K_SHORTEN_DIR_LENGTH=3
@@ -58,18 +62,60 @@ alias pst='ps -axwwo "lstart,pid,user,command" | sort -k5n -k2M -k3n -k4n -k6n'
 alias ffmpeg='ffmpeg -hide_banner'
 alias ffprobe='ffprobe -hide_banner'
 #
-#  Download HLS (m3u8) MP4 Stream to File
-#
-#
 
 
 ####################################################################################
 #  FUNCTIONS
 
 ##
+#  General Helpers
+#
+#
+#
+function unique-path
+{
+    if [[ $# < 1 ]] then;
+        echo "[ERROR] No file path was provided."
+        return 1
+    fi
+
+    local original_path="$1"
+    local unique_path="${original_path}"
+    local index=0
+
+    while [[ -e $unique_path ]] ; do
+
+        let index++
+        unique_path="${original_path:r}-$index.${original_path:e}"
+
+    done
+
+    echo "${unique_path}"
+}
+
+##
 #  ffmpeg Suite
 #
-#  Download m3u8 stream.  Parameter is stream URL.
+#
+#
+#
+function ff-codec
+{
+    if [[ $# < 1 ]] then;
+        echo "[ERROR] No input file was provided."
+        return 1
+    fi
+
+    local input_file="$1"
+
+    ffprobe -v error -select_streams v:0 -show_entries stream=codec_name -of default=nokey=1:noprint_wrappers=1 "${input_file}"
+
+    return $?
+}
+#
+#  ff-m3u8-to-mp4 <stream_url>
+#  Download HLS (m3u8) MP4 Stream to File
+#  Parameter: Stream URL.
 #
 function ff-m3u8-to-mp4
 {
@@ -81,8 +127,35 @@ function ff-m3u8-to-mp4
     local stream_url="$1"
     local output_file="${stream_url:h:t}-${stream_url:t:s/m3u8/mp4/}"
 
-    ffmpeg -i "${stream_url}" "${output_file}"
+    ffmpeg -i "${stream_url}" -preset slower "${output_file}"
+
+    return $?
 }
+#
+#
+#
+#
+function ff-mp4ify
+{
+    if [[ $# < 1 ]] then;
+        echo "[ERROR] No input file was provided."
+        return 1
+    fi
+
+    local input_file="$1"
+    local output_file=$(unique-path "${input_file:r}.mp4")
+    local ffmpeg_options=(-preset slower)
+
+    if [[ $(ff-codec "${input_file}") == "h264" ]] then;
+        ffmpeg_options=(-c:v copy)
+    fi
+
+    ffmpeg -i "${input_file}" $ffmpeg_options "${output_file}"
+
+    return $?
+}
+#
+
 
 ##
 #  Homebrew
